# Generated by Django 5.1.6 on 2025-04-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
